### ISSUE TITLE
Feature: Keep track of sync time of external mirror

### ISSUE THREAD

**Issue by BartOtten** [etix/mirrorbits#1]
Easy feature:
~~\- Make MirrorBits output a serverlist that is compatible with mirmon~~

Better feature:
Have something like "beaconFile" in config, which is a file that every server has with a timestamp in it. Save the content of beaconfile in the redis database and show the diff betweeen MirrorBits beaconFile and Mirrors beaconFile. 

This way, ?mirrorlist can show a table as:

| Mirrorname | Sync status |
| --- | --- |
| Server 1 | In sync |
| Server 3 | In sync |
| Server 4 | Out of sync by 10 hours and 14 seconds |
| Server 2 | Out of sync by 2 days, 12 hours and 14 seconds |

**Comment by MartijnKaijser** [comment]
Hi @etix is this something that is still on your to-do list? We have around 50 mirrors and it would greatly help to see if mirrors are still in sync

**Comment by etix** [comment]
Yes absolutely! These days I'm reworking the infrastructure to allow a seamless integration of new features like this one.

One of the other reason it took so long is because I didn't want to rely exclusively on a beacon file. The idea is not bad but usually requires every project wanting a similar feature to add and maintain a beacon with a specific format but I don't want to reinvent the wheel so I thought about it and I think I've found a more standard way that doesn't require a beacon file (but having one will improve the precision).

The idea will be to track the file with the most recent modification date both on the main repository and the mirrors and use it to compute the elapsed time between them. This requires the mirrors to preserve the modification time from the source repo (but it's pretty easy to do with rsync).

Without a beacon, you'll see if a mirror is in sync or not based on the last modification in the main repo (not very precise if you don't update the repo very often) but using a beacon updated every few minutes (no need for a specific format, using `touch` is enough) will give you a precise idea of the sync state of a mirror even if you don't modify or push files very often.

Would it be suitable for your use-case?

**Comment by MartijnKaijser** [comment]
We used mirmon in the past and just put a timestamp.txt in the root folder. I'm not familiar at all with server setup as we have more knowledgeable people doing that. I just maintain the mirror list and nudge them if they are out of sync.

**Comment by etix** [comment]
For the past two days I've been working on a way to do that without needing a special file on the mirror. As long as there is frequent updates on the master rsync the estimation will be pretty accurate. Updating a .trace file (or similar) every few minute can help otherwise.

If everything goes well it should land in the master later today.

**Comment by etix** [comment]
It turns out that my solution was not viable due to the diversity of FTP servers around (and their non-support of some extensions) and also bad configurations of the mirrors. Therefore I ended up using a trace file containing a timestamp like initially proposed by @BartOtten and in a fully mirmon-compatible manner.

**Comment by etix** [comment]
Don't forget to update your configuration file and set the `TraceFileLocation` accordingly. And of course it's still new and might not work as expected. However, don't be afraid to give it a try, it's already running in production on VideoLAN servers for two days now.
