### ISSUE TITLE
Allow individual mirror reporting

### ISSUE THREAD

**Issue by r0tekatze** [etix/mirrorbits#51]
Client sites at present don't have a requirement to include a link to report a mirror issue. Similarly, one cannot provide "feedback" in the form of location correction, which might be fairly important.

I mention this because there are a number of mirrors for a particular client that are adversely narrow in bandwidth - I just started a download of VLC that would have taken half an hour to complete had I not located the files on another mirror. 

Additionally, my development server is located in France. However, rather than a French provider, the provider selected is located in the British Midlands. Geographically, there are at least four better options.

**Comment by etix** [comment]
Can you elaborate please?

**Comment by r0tekatze** [comment]
Sorry, hit the enter key prematurely. Changing now

**Comment by etix** [comment]
I'm not sure handling reporting is mirrorbits' job. I suggest that you do that on your own code that queries the JSON output of mirrorbits and report to you directly so you can make the necessary changes manually.

Keep in mind that networks are quite unpredictable, a good situation can worsen and restore at any time so it's quite difficult to assess that a situation is permanent or not. Mirrorbits is meant for projects that can't or don't want to host their own mirrors, but if you can, doing anycast will always be a better choice since it takes the shortest route to the destination (taking temporary issues into account).

For the slow server situation, mirrorbits is only a best effort solution, it doesn't know how many bandwidth is still available on a given mirror and therefore randomizes the list of the selected mirrors to avoid hotspots. For sure you won't always get the closest (or fastest) server but overall the experience is definitely better than without any redirector. What we can consider in the future though is having a credit system so mirrors with a small amount of bandwidth cannot exceed some kind of download limit (per second, minute, hour) and in the meantime you'd better take down any mirror known to be slow but that's probably a different topic.

**Comment by r0tekatze** [comment]
Error reporting might be a bit overkill, but the ability to select a new mirror might be very useful for those situations where there is a bandwidth issue. That alone certainly wouldn't impact on the workload of those who manage mirrorbits. 

I just thought it might be a point to make, given that the likes of VideoLan have a significantly high number of users on a per-day basis, and it might make the impact of hosting mirrors a little more balanced.

When I referred to my development server, I meant that I had sampled the redirection by going to the VLC site and grabbing a copy. However, that's really only a secondary issue since the mirror was still fairly close by.

**Comment by etix** [comment]
On the VLC download page, there's a small button to show alternative mirrors. Also note that mirrorbits supports Metalinks in "redirect" mode, allowing some HTTP client to automatically switch to another mirror if necessary.

But anyway, this is not really a mirrorbits issue since it can be achieved by processing the mirrorbits JSON output and handling the response in PHP, Node.js, Go or any other language that can parse JSON to generate a webpage providing alternative URLs and/or adding some logic to report a slow download.
